### PR TITLE
Removed path truncation from to do list

### PR DESCRIPTION
**Pull request by Bilge**
You probably want to use [Pathogen](https://github.com/eloquent/pathogen) instead!

### CODE REVIEW

**Comment by okdana** [comment]
Whilst that looks really neat, i'm not sure if it achieves what i meant. I had envisioned functionality like, for example:

```
 // Returns '...|baz|qux'
(new \Dana\Truncator\Truncator())->truncateLeftBySegment('foo|bar|baz|qux', '|', 2);

 // Returns 'foo|...|qux'
(new \Dana\Truncator\Truncator())->truncateMiddleBySegment('foo|bar|baz|qux', '|', 2);

 // Returns 'foo|bar|...'
(new \Dana\Truncator\Truncator())->truncateRightBySegment('foo|bar|baz|qux', '|', 2);
```

Probably not astoundingly useful (not that the rest of this library is lol), but it was something that occurred to me when i was playing with my shell prompt, hence the file-path example i mentioned.

Is there some feature of Pathogen i missed that can accomplish that sort of thing?

**Comment by Bilge** [comment]
Oh, I see, the ellipses are actually in the output. For some reason, when I first read it, I thought they were just used to denote to the reader where the elements had been removed. I mean, I suppose that *is* what they are for, but I didn't realize they were included literally. Pathogen will not directly do that, of course, but you have the option of using it as a basis for doing path manipulations.

I only created this PR because I wanted to make you aware of the library, in case you wanted to build on it. Since GitHub doesn't support direct messaging this was the best thing I could come up with to let you know :smiley_cat:

**Comment by okdana** [comment]
Fair enough, thank you!

**Comment by Bilge** [comment]
xD

I was browsing your repos because I was using ddt, which is a really nice script! I think it should be a lot more popular, and probably would be, with a little promotion.

**Comment by okdana** [comment]
Thank you for saying so! It's pretty much just a re-imagining of `roundup`, which was created by someone a lot smarter than me, but i'm glad someone has a use for something i've done at least.

**Pull request closed without merging**
